language: python

cache:
  - pip

python:
  - "2.7.11"

sudo: false

install: pip install -r requirements.txt pylint

before_script:
  - export DATABASE_URL='sqlite:///local.db'
  - python models.py

script:
  - pylint -j $(nproc) *.py tests
  - python process.py
  - python united.py --light
  - python -m unittest discover tests
