version: '2'

services:
  anyway:
    # build: .
    image: uumpa/hasadna-anyway:fix_docker_test3
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=postgresql://anyway:anyway@db/anyway
    volumes:
      - .:/anyway
    restart: always
    depends_on:
      - db

  db:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=anyway
      - POSTGRES_USER=anyway
      - POSTGRES_DB=anyway
    restart: always
