name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: global add eslint --ignore-engines
      - run: eslint static/js --ignore-path=static/js/.eslintignore
