name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - run: rm -f .yarnclean
      - run: |
          yarn global add eslint --ignore-engines
          eslint static/js --ignore-path=static/js/.eslintignore
