name: CI
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt -r requirements.txt
    - name: Pylint
      run: |
        pylint anyway tests main.py
    - name: Running server
      run: |
        docker-compose up -d --build
    - name: Tests
      run: |
        pytest tests -m "not browser"
