name: CI
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set environment variables
      run: |
        export SAUCELABS_USERNAME=anyway
        export SAUCE_USERNAME=anyway
        export DATABASE_URL=postgresql://postgres@localhost/anyway
        echo "::set-env name=SAUCELABS_USERNAME::$SAUCELABS_USERNAME"
        echo "::set-env name=SAUCE_USERNAME::$SAUCE_USERNAME"
        echo "::set-env name=DATABASE_URL::$DATABASE_URL"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt -r requirements.txt
    - name: Pylint
      run: |
        pylint anyway tests main.py
    - name: Running server
      run: |
        docker-compose -f docker-compose-test.yml up -d --build
    - name: DB initialization
      run: |
        docker exec anyway ./main.py process registered-vehicles
        docker exec anyway ./main.py process cbs
    - name: Tests
      run: |
        pytest tests -m "not browser"
